const bombillerasLed = [
    {
        categoria: "bombilleria led",
        nombre: "DGP H4 P43 6500K UNIDAD",
        cantidad: 4,
        precioCosto: 0,
        precioVenta: 65000,
        precioVenta2: 0,
        precioVenta3: 65000,
    },
    {
        categoria: "bombilleria led",
        nombre: "BOSCH H4 LUZ BLANCA UNIDAD",
        cantidad: 10,
        precioCosto: 0,
        precioVenta: 75000,
        precioVenta2: 0,
        precioVenta3: 75000,
    },
    {
        categoria: "bombilleria led",
        nombre: "NARVA H4 P43 MOTO 6500K",
        cantidad: 0,
        precioCosto: 0,
        precioVenta: 50000,
        precioVenta2: 0,
        precioVenta3: 50000,
    },
    {
        categoria: "bombilleria led",
        nombre: "BICOLOR H4 P43",
        cantidad: 10,
        precioCosto: 0,
        precioVenta: 150000,
        precioVenta2: 0,
        precioVenta3: 150000,
    },
    {
        categoria: "bombilleria led",
        nombre: "H1 TIPO BOSCH XJUEGO",
        cantidad: 2,
        precioCosto: 0,
        precioVenta: 120000,
        precioVenta2: 0,
        precioVenta3: 120000,
    },
    {
        categoria: "bombilleria led",
        nombre: "H3 LUZ BLANCA TIPO BOSCH xJUEGO",
        cantidad: 4,
        precioCosto: 0,
        precioVenta: 120000,
        precioVenta2: 0,
        precioVenta3: 120000,
    },
    {
        categoria: "bombilleria led",
        nombre: "H7 BICOLOR X JUEGO",
        cantidad: 5,
        precioCosto: 0,
        precioVenta: 250000,
        precioVenta2: 0,
        precioVenta3: 250000,
    },
    {
        categoria: "bombilleria led",
        nombre: "H7 LUZ BLANCA CON VENTILADOR XJUEGO",
        cantidad: 1,
        precioCosto: 0,
        precioVenta: 95000,
        precioVenta2: 0,
        precioVenta3: 95000,
    },
    {
        categoria: "bombilleria led",
        nombre: "H1 TURBO LED XJUEGO",
        cantidad: 1,
        precioCosto: 0,
        precioVenta: 95000,
        precioVenta2: 0,
        precioVenta3: 95000,
    },
    {
        categoria: "bombilleria led",
        nombre: "1141 FLASHEO BLANCO -1F",
        cantidad: 10,
        precioCosto: 9200,
        precioVenta: 92000,
        precioVenta2: 12000,
        precioVenta3: 2800,
    },
    {
        categoria: "bombilleria led",
        nombre: "BOMBILLO 158 RGB MAS CONTROL",
        cantidad: 4,
        precioCosto: 15550,
        precioVenta: 62200,
        precioVenta2: 20000,
        precioVenta3: 4450,
    },

    {
        categoria: "bombilleria led",
        nombre: "MODULO LUPA BLANCA 1.5 W",
        cantidad: 4,
        precioCosto: 2900,
        precioVenta: 11600,
        precioVenta2: 5000,
        precioVenta3: 2100,
    },
    {
        categoria: "bombilleria led",
        nombre: "1141 LED FLASHEO BLANCO",
        cantidad: 10,
        precioCosto: 8000,
        precioVenta: 80000,
        precioVenta2: 10000,
        precioVenta3: 2000,
    },
    {
        categoria: "bombilleria led",
        nombre: "1034 LED FLASHEO BLANCO",
        cantidad: 10,
        precioCosto: 8000,
        precioVenta: 80000,
        precioVenta2: 10000,
        precioVenta3: 2000,
    },
    {
        categoria: "bombilleria led",
        nombre: "1034 BLANCO FIJO",
        cantidad: 10,
        precioCosto: 0,
        precioVenta: 10000,
        precioVenta2: 0,
        precioVenta3: 10000,
    },
    {
        categoria: "bombilleria led",
        nombre: "158 LED",
        cantidad: 46,
        precioCosto: 3500,
        precioVenta: 161000,
        precioVenta2: 5000,
        precioVenta3: 1500,
    },
    {
        categoria: "bombilleria led",
        nombre: "MODULO LUPA AMARILLO 1.5 W",
        cantidad: 6,
        precioCosto: 2000,
        precioVenta: 12000,
        precioVenta2: 5000,
        precioVenta3: 3000,
    },
    {
        categoria: "bombilleria led",
        nombre: "MODULO LUPA ROJO 1.5 W",
        cantidad: 14,
        precioCosto: 2000,
        precioVenta: 28000,
        precioVenta2: 5000,
        precioVenta3: 3000,
    },
    {
        categoria: "bombilleria led",
        nombre: "MODULO LUPA AZUL HIELO 1.5 W",
        cantidad: 40,
        precioCosto: 2000,
        precioVenta: 80000,
        precioVenta2: 5000,
        precioVenta3: 3000,
    },
    {
        categoria: "bombilleria led",
        nombre: "MODULO LUPA AZUL 1.5 W",
        cantidad: 11,
        precioCosto: 2000,
        precioVenta: 22000,
        precioVenta2: 5000,
        precioVenta3: 3000,
    },
    {
        categoria: "bombilleria led",
        nombre: "MODULO LUPA VERDE 1.5 W",
        cantidad: 4,
        precioCosto: 0,
        precioVenta: 0,
        precioVenta2: 5000,
        precioVenta3: 5000,
    },
    {
        categoria: "bombilleria led",
        nombre: "T5 BLANCO CANBUS",
        cantidad: 20,
        precioCosto: 2500,
        precioVenta: 50000,
        precioVenta2: 3500,
        precioVenta3: 1000,
    },
    {
        categoria: "bombilleria led",
        nombre: "T5 3 LED",
        cantidad: 4,
        precioCosto: 2500,
        precioVenta: 10000,
        precioVenta2: 3500,
        precioVenta3: 1000,
    },
    {
        categoria: "bombilleria led",
        nombre: "T5 1 LED",
        cantidad: 10,
        precioCosto: 2000,
        precioVenta: 20000,
        precioVenta2: 3000,
        precioVenta3: 1000,
    },

    // Puedes acceder a los elementos de la tabla como productos6[0].nombre, productos6[0].categoria, etc.

];

  // Puedes acceder a los elementos de la tabla como productos5[0].nombre, productos5[0].categoria, etc.
