const BUJIAS = [
    {
        categoria: "BUJIAS",
        nombre: "BUJIA FR8DCX 7957+19 BOSCH CORSA MITSUBISHI AVEO",
        cantidad: 21,
        precioCosto: 0,
        precioVenta: 12000,
        precioVenta2: 0,
        precioVenta3: 12000,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA 79080 BOSCH WOLKWAGEN",
        cantidad: 3,
        precioCosto: 0,
        precioVenta: 23000,
        precioVenta2: 0,
        precioVenta3: 23000,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA MOTORCRAFT INY. SP-500 REF AGSF22FM FORD, MAZDA 2, 3",
        cantidad: 4,
        precioCosto: 20000,
        precioVenta: 80000,
        precioVenta2: 24000,
        precioVenta3: 4000,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA 79075+40 BOSCH RENAULT CLIO",
        cantidad: 12,
        precioCosto: 0,
        precioVenta: 22000,
        precioVenta2: 0,
        precioVenta3: 22000,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA PRECALENTAMIENTO 205-PN138 KTC 205-MP75 KTC",
        cantidad: 3,
        precioCosto: 0,
        precioVenta: 25000,
        precioVenta2: 0,
        precioVenta3: 25000,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA BP5ES NGK STOCK 6511 CARBURACION",
        cantidad: 10,
        precioCosto: 0,
        precioVenta: 9500,
        precioVenta2: 0,
        precioVenta3: 9500,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA SP-423 MOTORCRAFT CARBURACION",
        cantidad: 8,
        precioCosto: 0,
        precioVenta: 9500,
        precioVenta2: 0,
        precioVenta3: 9500,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA MR43XLS CARBURACION ACDELCO",
        cantidad: 16,
        precioCosto: 0,
        precioVenta: 9500,
        precioVenta2: 0,
        precioVenta3: 9500,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA BKR5EY V-POWER STOCK 7390 CORSA MITSUBISHI AVEO",
        cantidad: 52,
        precioCosto: 6800,
        precioVenta: 353600,
        precioVenta2: 9500,
        precioVenta3: 2700,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA BKR5EY NGK STOCK 97799 BRASILERA MAZDA CORSA MITSUBISHI",
        cantidad: 0,
        precioCosto: 6600,
        precioVenta: 0,
        precioVenta2: 9500,
        precioVenta3: 2900,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA BKR5EY NGK STOCK 7390 V-POWER CORSA MITSUBISHI AVEO JAPONESA",
        cantidad: 7,
        precioCosto: 0,
        precioVenta: 9500,
        precioVenta2: 0,
        precioVenta3: 9500,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA MFR2LS ACDELCO CORSA MITSUBISHI AVEO",
        cantidad: 16,
        precioCosto: 0,
        precioVenta: 9500,
        precioVenta2: 0,
        precioVenta3: 9500,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA BCPR5ES NGK STOCK 6130 INY. RENAULT SUZUKY, SWIFT 1.6, MEGANE1,6 SCENIC",
        cantidad: 12,
        precioCosto: 6312,
        precioVenta: 75744,
        precioVenta2: 9000,
        precioVenta3: 2688,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA DCPR7E NGK STOCK 3932 INY. CHEVROLET VAN N200 ALTO 1.0 16V",
        cantidad: 10,
        precioCosto: 9303,
        precioVenta: 93030,
        precioVenta2: 15000,
        precioVenta3: 5697,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA LFR5A-11B NGK STOCK 6376 NISSAN FRONTIER 4.0, NISSAN NEW, PATHFINDER",
        cantidad: 14,
        precioCosto: 10681,
        precioVenta: 149534,
        precioVenta2: 16000,
        precioVenta3: 5319,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA LZKAR7A NGK STOCK 6799 RENAULT CLIO II 16V",
        cantidad: 2,
        precioCosto: 0,
        precioVenta: 19000,
        precioVenta2: 0,
        precioVenta3: 19000,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA YR7DC+41 BOSCH 79027",
        cantidad: 0,
        precioCosto: 0,
        precioVenta: 18000,
        precioVenta2: 0,
        precioVenta3: 18000,
    },
    {
        categoria: "BUJIAS",
        nombre: "BUJIA XU22EPR-U 3179 DENSO CORSA MITSUBISHI AVEO",
        cantidad: 3,
        precioCosto: 0,
        precioVenta: 18000,
        precioVenta2: 0,
        precioVenta3: 18000,
    },
];

  // Puedes acceder a los elementos de la tabla como productosBUJIAS[0].nombre, productosBUJIAS[0].categoria, etc.
