const pines =[
    {
      categoria: "PINES",
      nombre: "PIN 2 PINES",
      cantidad: 9,
      precioCosto: 0,
      precioVenta: 0,
      precioVenta2: 900,
      precioVenta3: 900,
    },
    {
      categoria: "PINES",
      nombre: "PIN 4 PINES",
      cantidad: 3,
      precioCosto: 0,
      precioVenta: 0,
      precioVenta2: 900,
      precioVenta3: 900,
    },
    {
      categoria: "PINES",
      nombre: "PIN TIPO PUNTILLA",
      cantidad: 4,
      precioCosto: 0,
      precioVenta: 0,
      precioVenta2: 900,
      precioVenta3: 900,
    },
    {
      categoria: "PINES",
      nombre: "PIN 6 PINES",
      cantidad: 15,
      precioCosto: 0,
      precioVenta: 0,
      precioVenta2: 900,
      precioVenta3: 900,
    },
    {
      categoria: "PINES",
      nombre: "PINES HEMBRAS",
      cantidad: 9,
      precioCosto: 0,
      precioVenta: 0,
      precioVenta2: 900,
      precioVenta3: 900,
    },
  ];
  