const sensores = [
    {
        categoria: "SENSORES",
        nombre: "SENSOR EJE LEVAS OPTRA 1.4 1.6, AVEO 1.4 1.6, EMOTION G+",
        cantidad: 1,
        precioCosto: 100000,
        precioVenta: 140000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR DE PRESION MAT SPARK 1.0",
        cantidad: 2,
        precioCosto: 70000,
        precioVenta: 98000,
    },
    {
        categoria: "SENSORES",
        nombre: "TPS SENSOR 7230 DW RAICER, BLUCER, GIRO ANTIHORARIO",
        cantidad: 1,
        precioCosto: 50000,
        precioVenta: 85000,
    },
    {
        categoria: "SENSORES",
        nombre: "TPS SENSOR 7231 , AVEO SPARK, CORSA, OPTRA 18",
        cantidad: 4,
        precioCosto: 85000,
        precioVenta: 105000,
    },
    {
        categoria: "SENSORES",
        nombre: "VALVULA IAC NPC 42101 RENAULT LOGAN CLIO MEGAN",
        cantidad: 2,
        precioCosto: 50000,
        precioVenta: 68000,
    },
    {
        categoria: "SENSORES",
        nombre: "TPS SENSOR 7262 RENAULT CLIO II - MEGANE - TODOS",
        cantidad: 1,
        precioCosto: 90000,
        precioVenta: 120000,
    },
    {
        categoria: "SENSORES",
        nombre: "TPS SENSOR 7265 FIAT",
        cantidad: 1,
        precioCosto: 45000,
        precioVenta: 70000,
    },
    {
        categoria: "SENSORES",
        nombre: "NPC 39303 IAC CORSA AVEO",
        cantidad: 3,
        precioCosto: 50000,
        precioVenta: 78000,
    },
    {
        categoria: "SENSORES",
        nombre: "THOMSON 7448 PARA CORSA 1.8 N200-3000",
        cantidad: 1,
        precioCosto: 52000,
        precioVenta: 85000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR KTC 255-011 POSICION CIGÜEÑAL, AVEO, OPTRA 1.6",
        cantidad: 1,
        precioCosto: 38000,
        precioVenta: 60000,
    },
    {
        categoria: "SENSORES",
        nombre: "THOMSON 7048 SENSOR POSICION CIGÜEÑAL DE CORSA",
        cantidad: 1,
        precioCosto: 95000,
        precioVenta: 125000,
    },
    {
        categoria: "SENSORES",
        nombre: "THOMSON 70560 SENSOR VOLANTE MOTOR ATOS 1.3 3 PINES",
        cantidad: 2,
        precioCosto: 55000,
        precioVenta: 85000,
    },
    {
        categoria: "SENSORES",
        nombre: "THOMSON CKP SENSOR 70509 VOLANTE MOTOR OPOSICION DE CIGÜEÑAL R. LOGAN TWINGO FASE II 8V",
        cantidad: 2,
        precioCosto: 55000,
        precioVenta: 75000,
    },
    {
        categoria: "SENSORES",
        nombre: "THOMSON 73020, SENSOR DE VELOCIDAD CORSA",
        cantidad: 1,
        precioCosto: 70000,
        precioVenta: 100000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR VELOCIDAD MONTERO L200, S-1094",
        cantidad: 1,
        precioCosto: 0,
        precioVenta: 0,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR VOLANTE MOTOR O POSC. CIGÜEÑAL THOMSON 7051 R. MEGANE - CLIO II SYMBOL 16V.",
        cantidad: 1,
        precioCosto: 55000,
        precioVenta: 95000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR POSI CIGÜEÑAL CHRONS, SPARK GT",
        cantidad: 1,
        precioCosto: 70000,
        precioVenta: 100000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR DE OXIGENO 234 -6003L 3 CABLES",
        cantidad: 1,
        precioCosto: 170000,
        precioVenta: 205000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR DE OXIGENO 7773 5. OX. 3 CABLES.",
        cantidad: 1,
        precioCosto: 120000,
        precioVenta: 150000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR DE OXIGENO 7774 5. OX. 4 CABLES.",
        cantidad: 1,
        precioCosto: 130000,
        precioVenta: 165000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR DE OXIGENO 7772 2 CABLES THOMSON",
        cantidad: 3,
        precioCosto: 100000,
        precioVenta: 130000,
    },
    {
        categoria: "SENSORES",
        nombre: "KTC PN: 255-053 OXIGENO 1CABLE",
        cantidad: 3,
        precioCosto: 95000,
        precioVenta: 125000,
    },
    {
        categoria: "SENSORES",
        nombre: "OXIGENO THOMSON 7867 PACHA DOS CABLS",
        cantidad: 2,
        precioCosto: 150000,
        precioVenta: 185000,
    },
    {
        categoria: "SENSORES",
        nombre: "OXIGENO THOMSON 7891 CON PACHA 4 CABLES",
        cantidad: 1,
        precioCosto: 160000,
        precioVenta: 195000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR DE VELOCIDAD 7328 R. TWINGO 16V",
        cantidad: 1,
        precioCosto: 35000,
        precioVenta: 55000,
    },
    {
        categoria: "SENSORES",
        nombre: "SENSOR MAP 7120 R9 INY. R21 LAGUNA CLIO",
        cantidad: 1,
        precioCosto: 120000,
        precioVenta: 150000,
    },
];
