const terminales = [
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE COBRE 50AMP",
        cantidad: 19,
        precioCosto: 0,
        precioVenta: 2000,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE COBRE 70AMP",
        cantidad: 15,
        precioCosto: 0,
        precioVenta: 2500,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE COBRE 100AMP",
        cantidad: 27,
        precioCosto: 0,
        precioVenta: 3500,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE COBRE 150AMP",
        cantidad: 4,
        precioCosto: 0,
        precioVenta: 4500,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE COBRE 250AMP",
        cantidad: 2,
        precioCosto: 0,
        precioVenta: 6000,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA HEMBRA PEQUEÑA",
        precioCosto: 0,
        precioVenta: 200,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA HEMBRA MEDIANA",
        precioCosto: 0,
        precioVenta: 200,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA HEMBRA GRANDE",
        precioCosto: 0,
        precioVenta: 300,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA HEMBRA EXTRA GRANDE",
        precioCosto: 0,
        precioVenta: 500,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA MACHO PEQUEÑA",
        precioCosto: 0,
        precioVenta: 200,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA MACHO MEDIANA",
        precioCosto: 0,
        precioVenta: 200,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA MACHO GRANDE",
        precioCosto: 0,
        precioVenta: 300,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL PLANA MACHO EXTRA GRANDE",
        precioCosto: 0,
        precioVenta: 800,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE OJO PEQUEÑA 5/32",
        precioCosto: 0,
        precioVenta: 250,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE OJO MEDIANA 3/16",
        precioCosto: 0,
        precioVenta: 300,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE OJO MEDIANA 1/4",
        precioCosto: 0,
        precioVenta: 300,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL DE OJO GRANDE 5/16",
        precioCosto: 0,
        precioVenta: 300,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL REDONDA HEMBRA",
        precioCosto: 0,
        precioVenta: 200,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL REDONDA MACHO",
        precioCosto: 0,
        precioVenta: 200,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL REDONDA HEMBRA 1/4",
        precioCosto: 0,
        precioVenta: 500,
    },
    {
        categoria: "TERMINALES",
        nombre: "TERMINAL REDONDA HEMBRA 3/16",
        precioCosto: 0,
        precioVenta: 300,
    },
    {
        categoria: "TERMINALES",
        nombre: "PROTECTOR PARA TERMINAL REDONDO",
        precioCosto: 0,
        precioVenta: 200,
    },
    {
        categoria: "TERMINALES",
        nombre: "PROTECTOR PARA FUSIBLE",
        precioCosto: 0,
        precioVenta: 0,
    },
];
